### ISSUE TITLE
PreNet5Lock uses different namespace

### ISSUE THREAD

**Issue by CptWesley** [MarkCiliaVincenti/Backport.System.Threading.Lock#3]
The `PreNet5Lock` version of `Lock` resides in the the `Backport.System.Threading` namespace rather than the `System.Threading` namespace. Is this intentional? To me this seems a bit counter intuitive for projects multi-targeting modern .NET and older .NET Standard or .NET Framework projects. Just for my own clarity: why exactly are there two different types?

**Comment by MarkCiliaVincenti** [comment]
Yes, it is intentional. `PreNet5Lock` exists purely because before .NET 5.0 it was possible to abort threads. If the normal lock was to be used on, say, .NET Core 3.1, the code would now be lowered by the compiler, because System.Threading.Lock is now 'reserved', to code that is NOT hardened against thread aborts, making it possible that a thread abort would leave a lock taken and other threads would not be able to enter. Thus, in order to not introduce new bugs, the normal locking class was only made available from .NET 5 to .NET 8.

If you are targeting something earlier than .NET 5, you need to use the factory method as per https://github.com/MarkCiliaVincenti/Backport.System.Threading.Lock?tab=readme-ov-file#factory-method-if-targeting-frameworks-prior-to-net-50

**Comment by CptWesley** [comment]
I see. Doesn't this cause similar issues with regards to the type forwarding that you also brought up in #1 ?

**Comment by MarkCiliaVincenti** [comment]
That's why there is the warning that who uses it MUST also target net9.
